version: '3'
services:
  app:
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000 # Porta do servidor de desenvolvimento do Vite
    volumes:
      - .:/app
